### ISSUE TITLE
Send Action Metric

### ISSUE THREAD

**Issue by korgon** [searchspring/snap-action#24]
When the action runs, upload a file to S3 for metric usage.

Example for site _demo.shopify_ running the action and it completing successfully:

SnapAction[demo.shopify]-2022_5_10_1832.json
```
{
	"timestamp": "2022-05-11T00:32:20.237Z",
	"type": "snap-action",
	"data": {
		"repository": "demo.shopify",
		"conclusion": "success"
	}
}
```

Example for site _demo.shopify_ running the action and it **NOT** completing successfully:

SnapAction[demo.shopify]-2022_5_10_1832.json
```
{
	"timestamp": "2022-05-11T00:32:20.237Z",
	"type": "snap-action",
	"data": {
		"repository": "demo.shopify",
		"conclusion": "failure"
	}
}
```

Can use code from Snap repo for example of building and uploading files: https://github.com/searchspring/snap/pull/492 

Action can use logic similar to:
```
steps:
  - name: Step To run on failure
    if: ${{ failure() }}
```

**Comment by dkonieczek** [comment]
Ready for review.
A run using this branch can be seen here: https://github.com/searchspring-implementations/stfrock.com.au/runs/6396473198?check_suite_focus=true
