### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by korgon** [searchspring/snap-action#39]
For rollback purposes and versioning, we need to implement tagging for repositories.

Tags should be generated based on the `version` found in package.json. If a tag with that version already exists we should postfix an update version to the end.

Examples:
```
0.32.0
0.32.0-1
0.32.0-2
0.32.0-3
```

---

Currently we upload the bundle (and chunked files) to: https://snapui.searchspring.io/{ siteId }/bundle.js
And also for each branch we upload to: https://snapui.searchspring.io/{ siteId }/{ branch }/bundle.js

We also need to upload versioned builds (builds from production) to an additional location on the CDN: https://snapui.searchspring.io/{ siteId }/{ version }/bundle.js

**Comment by dkonieczek** [comment]
Ready to release. Waiting for the right time
